name: CI
on: 
   push:
     branches:    
      - main
   pull_request:
     branches:
      - main
   workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Run Test
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap
    - name: Create tests reports
      id: test_module
      uses: zyborg/pester-tests-report@v1
      with:
        test_results_path: tests/out/testResults.xml
        exclude_tags: skip_ci
        report_name: "module_tests_${{ matrix.os }}"
        report_title: My Module Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output_level: normal
        tests_fail_step: true
    - name: Dump Tests
      shell: pwsh
      run: |
        Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
        Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
        Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'
    

