name: Create release
on:
  push:
    tags:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Test
        id: run_test
        shell: pwsh
        run: ./build.ps1 -Task Test -Bootstrap
      - name: Create tests reports
        id: test_module
        uses: zyborg/pester-tests-report@v1
        with:
          test_results_path: tests/out/testResults.xml
          exclude_tags: skip_ci
          report_name: "module_tests_${{ matrix.os }}"
          report_title: My Module Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_level: diagnostic
          tests_fail_step: true

      - name: Build Changelog
        id: build_changelog
        uses: Bullrich/generate-release-changelog@master
        env:
          REPO: ${{ github.repository }}
      - name: Clean Changelog
        id: modified
        run: |
          set -o noglob
          log=$(cat << "EOF" | grep -v :robot: | tac
          ${{steps.build_changelog.outputs.changelog}}
          EOF
          )
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"
          echo "::set-output name=modified::$log"
      
      - name: Release on Github
        uses: ncipollo/release-action@v1
        with:
          name: ${{github.ref_name}}
          artifacts: "LICENSE"
          body: ${{ steps.modified.outputs.modified }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release on Powershell Gallery
        shell: pwsh
        run: Publish-Module -Path ./BioNameGenerator -NuGetApiKey ${{ secrets.PSGALLERY_KEY }} -ReleaseNotes ${{ steps.modified.outputs.modified }}
          
