name: Installation Test
on:
  release:
    types: [published, released]
  workflow_dispatch:
jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
     - name: Installation on ${{ matrix.os }}
       shell: pwsh
       run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module BioNameGenerator 
          Get-RandomKeyword
          Get-RandomPhrase
